### ISSUE TITLE
Fail 'make test'

### ISSUE THREAD

**Issue by asamats** [spiral/roadrunner#143]
What I do:
git clone ...
git checkout v1.3.7
go mod download
make
make test
What I got:
```
=== RUN   TestHandler_Empty_User_Agent
--- FAIL: TestHandler_Empty_User_Agent (0.04s)
    handler_test.go:205: 
        	Error Trace:	handler_test.go:205
        	Error:      	Received unexpected error:
        	            	Get http://localhost:8088?hello=world: read tcp 127.0.0.1:55254->127.0.0.1:8088: read: connection reset by peer
        	Test:       	TestHandler_Empty_User_Agent
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa7d014]

goroutine 7 [running]:
testing.tRunner.func1(0xc000106100)
	/usr/local/go/src/testing/testing.go:830 +0x69d
panic(0xb2bc20, 0x108b1d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/spiral/roadrunner/service/http.TestHandler_Empty_User_Agent(0xc000106100)
	/home/asamat/Projects/labs/roadrunner/service/http/handler_test.go:206 +0x9a4
testing.tRunner(0xc000106100, 0xbd5ae0)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x65b
FAIL	github.com/spiral/roadrunner/service/http	0.158s
Makefile:12: recipe for target 'test' failed
make: *** [test] Error 1
```

Ubuntu 18.04
go1.12.1
php 7.3.4

**Comment by wolfy-j** [comment]
Hmmm,

it works well locally and in travis. Is it possible that test port 8888 is used by another application in your environment?

**Comment by asamats** [comment]
Thanks @wolfy-j I didn't look port. It was influxdb.
