### ISSUE TITLE
[BUG] Error after set http.workers.user

### ISSUE THREAD

**Issue by lanlin** [spiral/roadrunner#375]
```shell
time="2020-10-27T11:59:01+08:00" level=debug msg="[headers]: disabled"
time="2020-10-27T11:59:01+08:00" level=debug msg="[static]: disabled"
time="2020-10-27T11:59:02+08:00" level=debug msg="[rpc]: started"
time="2020-10-27T11:59:02+08:00" level=debug msg="[http]: started"
time="2020-10-27T11:59:02+08:00" level=debug msg="[metrics]: started"
time="2020-10-27T11:59:02+08:00" level=debug msg="[health]: started"
time="2020-10-27T11:59:02+08:00" level=debug msg="[reload]: started"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x151d6c6]

goroutine 49 [running]:
github.com/spiral/roadrunner.newWorker(0x0, 0xc00007c190, 0xc0002e2300, 0xc00023c001)
	github.com/spiral/roadrunner/worker.go:55 +0x26
github.com/spiral/roadrunner.(*PipeFactory).SpawnWorker(0x1d73d70, 0x0, 0xc000cf8d90, 0x10054b0, 0x60)
	github.com/spiral/roadrunner/pipe_factory.go:25 +0x32
github.com/spiral/roadrunner.(*StaticPool).createWorker(0xc000a540e0, 0xc000a540e0, 0xc0004ac120, 0xc000204060)
	github.com/spiral/roadrunner/static_pool.go:267 +0x4f
github.com/spiral/roadrunner.NewPool(0xc0002e22d0, 0x190ca60, 0x1d73d70, 0x4, 0x0, 0xdf8475800, 0xdf8475800, 0xc000cf8e98, 0xc000cf8e98, 0x100e0f8)
	github.com/spiral/roadrunner/static_pool.go:75 +0x1ef
github.com/spiral/roadrunner.(*Server).Start(0xc0002da000, 0x0, 0x0)
	github.com/spiral/roadrunner/server.go:96 +0x129
github.com/spiral/roadrunner/service/http.(*Service).Serve(0xc000150420, 0x0, 0x0)
	github.com/spiral/roadrunner/service/http/service.go:154 +0x3ab
github.com/spiral/roadrunner/service.(*container).Serve.func1(0xc00020c100, 0xc0001ace10)
	github.com/spiral/roadrunner/service/container.go:177 +0xbc
created by github.com/spiral/roadrunner/service.(*container).Serve
	github.com/spiral/roadrunner/service/container.go:174 +0x17e
```

all users were not working, even set to root.
but after comment out this line, it works fine.

**Comment by 48d90782** [comment]
@lanlin What version of RR do you use?

**Comment by 48d90782** [comment]
@lanlin To use that feature you should run RR from the root with the `user` option in the config.

**Comment by lanlin** [comment]
PHP 7.4.4 (cli) (built: Mar 20 2020 16:29:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans

RoadRunner, PHP Application Server
Version: 1.8.4, 2020-10-21T14:07:46+0300

mac os 10.15.7

I run RR with sudo but it not working no matter any user set to `http.workers.user`

**Comment by 48d90782** [comment]
@lanlin At the moment, this is the Linux only feature.

**Comment by lanlin** [comment]
@48d90782 so sad to hear that, would it be supported in future?

**Comment by 48d90782** [comment]
@lanlin Hard to say, but you may create a ticket and if that feature is really required by the community, we will definitely support it :)

**Comment by lanlin** [comment]
@48d90782 ok, thanks very much
