### ISSUE TITLE
[BUG] RR2 fails on 'rr workers' when http disabled

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#515]
I tried this code:

```go
./rr workers
```

Config:

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "localhost:7233"
  activities:
    num_workers: 10

logs:
  level: debug
  channels:
    temporal:
      level: error
```

I expected to see this happen: see only workers from enabled plugins

Instead, this happened: 

```
2021/01/31 08:12:23     DEBUG   informer        Started List method
2021/01/31 08:12:23     DEBUG   informer        list of services        {"list": ["http", "workflows"]}
2021/01/31 08:12:23     DEBUG   informer        successfully finished List method
2021/01/31 08:12:23     DEBUG   informer        started Workers method  {"service": "http"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x789326]

goroutine 63182 [running]:
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).Workers(0xc000ab0280, 0xc0007fac00, 0xc000bf9480, 0x4)
        github.com/spiral/roadrunner/v2/plugins/http/plugin.go:306 +0x46
github.com/spiral/roadrunner/v2/plugins/informer.(*Plugin).Workers(0xc000a82380, 0xc000bf9480, 0x4, 0xc000fb5de0, 0x2, 0x2, 0xc000fe7bd0, 0xee5d0)
        github.com/spiral/roadrunner/v2/plugins/informer/plugin.go:31 +0x202
github.com/spiral/roadrunner/v2/plugins/informer.(*rpc).Workers(0xc000bdf360, 0xc000bf9480, 0x4, 0xc000fb5da0, 0x0, 0x0)
        github.com/spiral/roadrunner/v2/plugins/informer/rpc.go:37 +0x11f
reflect.Value.call(0xc000200e40, 0xc0001106e8, 0x13, 0x1154ae8, 0x4, 0xc000fe7f08, 0x3, 0x3, 0xc000fe7e98, 0xeef9f, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000200e40, 0xc0001106e8, 0x13, 0xc000fe7f08, 0x3, 0x3, 0xe, 0x1b65ce0, 0xc000e1cde8)
        reflect/value.go:337 +0xc5
net/rpc.(*service).call(0xc000913dc0, 0xc00029abe0, 0xc001122758, 0xc001122760, 0xc00037fb80, 0xc000fb5980, 0xf5a300, 0xc000dc6f70, 0x198, 0xf20d60, ...)
        net/rpc/server.go:377 +0x189
created by net/rpc.(*Server).ServeCodec
        net/rpc/server.go:474 +0x445

```
The version of RR used: v2.0.0-beta9

Errortrace, Backtrace or Panictrace
```
2021/01/31 08:12:23     DEBUG   informer        Started List method
2021/01/31 08:12:23     DEBUG   informer        list of services        {"list": ["http", "workflows"]}
2021/01/31 08:12:23     DEBUG   informer        successfully finished List method
2021/01/31 08:12:23     DEBUG   informer        started Workers method  {"service": "http"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x789326]

goroutine 63182 [running]:
github.com/spiral/roadrunner/v2/plugins/http.(*Plugin).Workers(0xc000ab0280, 0xc0007fac00, 0xc000bf9480, 0x4)
        github.com/spiral/roadrunner/v2/plugins/http/plugin.go:306 +0x46
github.com/spiral/roadrunner/v2/plugins/informer.(*Plugin).Workers(0xc000a82380, 0xc000bf9480, 0x4, 0xc000fb5de0, 0x2, 0x2, 0xc000fe7bd0, 0xee5d0)
        github.com/spiral/roadrunner/v2/plugins/informer/plugin.go:31 +0x202
github.com/spiral/roadrunner/v2/plugins/informer.(*rpc).Workers(0xc000bdf360, 0xc000bf9480, 0x4, 0xc000fb5da0, 0x0, 0x0)
        github.com/spiral/roadrunner/v2/plugins/informer/rpc.go:37 +0x11f
reflect.Value.call(0xc000200e40, 0xc0001106e8, 0x13, 0x1154ae8, 0x4, 0xc000fe7f08, 0x3, 0x3, 0xc000fe7e98, 0xeef9f, ...)
        reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000200e40, 0xc0001106e8, 0x13, 0xc000fe7f08, 0x3, 0x3, 0xe, 0x1b65ce0, 0xc000e1cde8)
        reflect/value.go:337 +0xc5
net/rpc.(*service).call(0xc000913dc0, 0xc00029abe0, 0xc001122758, 0xc001122760, 0xc00037fb80, 0xc000fb5980, 0xf5a300, 0xc000dc6f70, 0x198, 0xf20d60, ...)
        net/rpc/server.go:377 +0x189
created by net/rpc.(*Server).ServeCodec
        net/rpc/server.go:474 +0x445
```

**Comment by wolfy-j** [comment]
Also fails on reset and reloader.

**Comment by wolfy-j** [comment]
Also, the informer did not pick up the "activities" plugin for some reason.

**Comment by 48d90782** [comment]
https://github.com/spiral/endure/issues/81

**Comment by 48d90782** [comment]
fixed by https://github.com/spiral/endure/pull/83
Endure version: `beta.22`
