### ISSUE TITLE
[BUG, RR2] Metrics example not working

### ISSUE THREAD

**Issue by dstrop** [spiral/roadrunner#571]
i am testing v2 and it seems the example code is broken

i have taken code from https://github.com/spiral/roadrunner-metrics readme

and got
```
Next Spiral\Goridge\Exception\RelayException: unable to establish connection tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/SocketRelay.php:222
```
<details><summary>full error</summary>
<p>

```
2021-03-03T22:11:38.947Z	DEBUG	server	server/plugin.go:244	Warning: socket_connect(): unable to connect [111]: Connection refused in /repo/vendor/spiral/goridge/src/SocketRelay.php on line 218
2021-03-03T22:11:38.947Z	DEBUG	server	server/plugin.go:244	Fatal error: Uncaught Spiral\Goridge\Exception\RelayException: Connection refused in /repo/vendor/spiral/goridge/src/SocketRelay.php:219
Stack trace:
#0 /repo/vendor/spiral/goridge/src/SocketRelay.php(188): Spiral\Goridge\SocketRelay->connect()
#1 /repo/vendor/spiral/goridge/src/RPC/RPC.php(78): Spiral\Goridge\SocketRelay->send(Object(Spiral\Goridge\Frame))
#2 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(94): Spiral\Goridge\RPC\RPC->call('Declare', Array)
#3 /repo/worker.php(23): Spiral\RoadRunner\Metrics\Metrics->declare('test', Object(Spiral\RoadRunner\Metrics\Collector))
#4 {main}

Next Spiral\Goridge\Exception\RelayException: unable to establish connection tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/SocketRelay.php:222
Stack trace:
#0 /repo/vendor/spiral/goridge/src/SocketRelay.php(188): Spiral\Goridge\SocketRelay->connect()
#1 /repo/vendor/spiral/goridge/src/RPC/RPC.php(78): Spiral\Goridge\SocketRelay->send(Object(Spiral\Goridge\Frame))
#2 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(94): Spiral\Goridge\RPC\RPC->call('Declare', Array)
#3 /repo/worker.php(23): Spiral\RoadRunner\Metrics\Metrics->declare('test', Object(Spiral\RoadRunner\Metrics\Collector))
#4 {main}
  thrown in /repo/vendor/spiral/goridge/src/SocketRelay.php on line 222
2021/03/03 22:11:39 handle_serve_command: Serve error:
	endure_start:
	endure_serve_internal: Function call error:
	endure_call_serve_fn: got initial serve error from the Vertex http.Plugin, stopping execution, error: http_plugin_serve: WorkerAllocate:
	server_plugin_new_worker_pool:
	static_pool_initialize:
	allocate workers:
	factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed
```
</p>
</details>

it only worked when i moved metric declaration into the while loop

also if i moved metric declaration from code to .rr.yaml as in https://roadrunner.dev/docs/beep-beep-metrics
i got as a response
```
error 'metrics_plugin_add: collector test does not support method `Add`
```
<details><summary>full response and logs from roadrunner</summary>
<p>

```
1 error occurred:
	* error encoder: SoftJobError:
	sync_worker_exec_payload: Spiral\Goridge\RPC\Exception\ServiceException: error 'metrics_plugin_add: collector test does not support method `Add`; metrics_plugin_add: collector test does not support method `Add`' on tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/RPC/RPC.php:120
Stack trace:
#0 /repo/vendor/spiral/goridge/src/RPC/RPC.php(93): Spiral\Goridge\RPC\RPC->decodeResponse(Object(Spiral\Goridge\Frame))
#1 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(44): Spiral\Goridge\RPC\RPC->call('Add', Array)
#2 /repo/worker.php(31): Spiral\RoadRunner\Metrics\Metrics->add('test', 1)
#3 {main}

Next Spiral\RoadRunner\Metrics\Exception\MetricsException: error 'metrics_plugin_add: collector test does not support method `Add`; metrics_plugin_add: collector test does not support method `Add`' on tcp://127.0.0.1:6001 in /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php:46
Stack trace:
#0 /repo/worker.php(31): Spiral\RoadRunner\Metrics\Metrics->add('test', 1)
#1 {main}
```

logs from roadrunner
```
2021-03-03T22:35:32.740Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 20}
2021-03-03T22:35:32.761Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 21}
2021-03-03T22:35:32.783Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 22}
2021-03-03T22:35:32.804Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 23}
2021-03-03T22:35:32.805Z	DEBUG	RPC	rpc/plugin.go:86	Started RPC service	{"address": "tcp://127.0.0.1:6001", "services": ["metrics", "informer", "resetter"]}
2021-03-03T22:35:37.604Z	INFO	metrics	metrics/rpc.go:29	adding metric	{"name": "test", "value": 1, "labels": []}
2021-03-03T22:35:37.606Z	DEBUG	server	server/plugin.go:226	worker destructed	{"pid": 20}
2021-03-03T22:35:37.655Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 30}
```
</p>
</details>

```yaml
metrics:
  address: "0.0.0.0:8081"
  collect:
    test:
      type: counter
```

but the roadrunner clearly knows the metric as its not throwing
```
2021-03-03T22:40:45.545Z	ERROR	metrics	metrics/rpc.go:32	undefined collector	{"collector": "test"}
```

The version of RR used: v2.0.0

**Comment by wolfy-j** [comment]
Can you show full config file? Are you sure that RPC enabled?

**Comment by 48d90782** [comment]
@dstrop Could you please show the full config (`.rr.yaml`) ?

**Comment by dstrop** [comment]
i took both from https://github.com/spiral/roadrunner-metrics
<details><summary>.rr.yaml</summary>
<p>

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"

metrics:
  address: "0.0.0.0:8081"

```
</p>
</details>

<details><summary>worker.php</summary>
<p>

```php
<?php

use Spiral\Goridge;
use Spiral\RoadRunner;
use Nyholm\Psr7\Factory;

ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

$worker = new RoadRunner\Http\PSR7Worker(
	RoadRunner\Worker::create(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory()
);

$metrics = new RoadRunner\Metrics\Metrics(
	Goridge\RPC\RPC::create(RoadRunner\Environment::fromGlobals()->getRPCAddress())
);

$metrics->declare(
	'test',
	RoadRunner\Metrics\Collector::counter()->withHelp('Test counter')
);

while ($req = $worker->waitRequest()) {
	try {
		$rsp = new \Nyholm\Psr7\Response();
		$rsp->getBody()->write("hello world");

		$metrics->add('test', 1);

		$worker->respond($rsp);
	} catch (\Throwable $e) {
		$worker->getWorker()->error((string)$e);
	}
}

```
</p>
</details>

and with this i got the
```
Next Spiral\Goridge\Exception\RelayException: unable to establish connection tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/SocketRelay.php:222
```

<details><summary>full error</summary>
<p>

```
2021-03-04T08:36:03.389Z	DEBUG	server	server/plugin.go:244	Warning: socket_connect(): unable to connect [111]: Connection refused in /repo/vendor/spiral/goridge/src/SocketRelay.php on line 218
2021-03-04T08:36:03.389Z	DEBUG	server	server/plugin.go:244	Fatal error: Uncaught Spiral\Goridge\Exception\RelayException: Connection refused in /repo/vendor/spiral/goridge/src/SocketRelay.php:219
Stack trace:
#0 /repo/vendor/spiral/goridge/src/SocketRelay.php(188): Spiral\Goridge\SocketRelay->connect()
#1 /repo/vendor/spiral/goridge/src/RPC/RPC.php(78): Spiral\Goridge\SocketRelay->send(Object(Spiral\Goridge\Frame))
#2 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(94): Spiral\Goridge\RPC\RPC->call('Declare', Array)
#3 /repo/worker.php(23): Spiral\RoadRunner\Metrics\Metrics->declare('test', Object(Spiral\RoadRunner\Metrics\Collector))
#4 {main}

Next Spiral\Goridge\Exception\RelayException: unable to establish connection tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/SocketRelay.php:222
Stack trace:
#0 /repo/vendor/spiral/goridge/src/SocketRelay.php(188): Spiral\Goridge\SocketRelay->connect()
#1 /repo/vendor/spiral/goridge/src/RPC/RPC.php(78): Spiral\Goridge\SocketRelay->send(Object(Spiral\Goridge\Frame))
#2 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(94): Spiral\Goridge\RPC\RPC->call('Declare', Array)
#3 /repo/worker.php(23): Spiral\RoadRunner\Metrics\Metrics->declare('test', Object(Spiral\RoadRunner\Metrics\Collector))
#4 {main}
  thrown in /repo/vendor/spiral/goridge/src/SocketRelay.php on line 222
2021/03/04 08:36:03 handle_serve_command: Serve error:
	endure_start:
	endure_serve_internal: Function call error:
	endure_call_serve_fn: got initial serve error from the Vertex http.Plugin, stopping execution, error: http_plugin_serve: WorkerAllocate:
	server_plugin_new_worker_pool:
	static_pool_initialize:
	allocate workers:
	factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed

```
</p>
</details>

what else i tried:

i tried moving the metrics declaration into the while loop

<details><summary>worker.php</summary>
<p>

```php
<?php

use Spiral\Goridge;
use Spiral\RoadRunner;
use Nyholm\Psr7\Factory;

ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

$worker = new RoadRunner\Http\PSR7Worker(
	RoadRunner\Worker::create(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory()
);

$metrics = new RoadRunner\Metrics\Metrics(
	Goridge\RPC\RPC::create(RoadRunner\Environment::fromGlobals()->getRPCAddress())
);

while ($req = $worker->waitRequest()) {
	try {
		$rsp = new \Nyholm\Psr7\Response();
		$rsp->getBody()->write("hello world");

		$metrics->declare(
			'test',
			RoadRunner\Metrics\Collector::counter()->withHelp('Test counter')
		);

		$metrics->add('test', 1);

		$worker->respond($rsp);
	} catch (\Throwable $e) {
		$worker->getWorker()->error((string)$e);
	}
}

```
</p>
</details>

like this it works except the repeated error
```
2021-03-04T08:42:49.598Z	ERROR	metrics	metrics/rpc.go:177	metric with provided name already exist	{"name": "test", "type": "counter", "namespace": ""}
```

i also tried using example from https://roadrunner.dev/docs/beep-beep-metrics
<details><summary>.rr.yaml</summary>
<p>

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"

metrics:
  address: "0.0.0.0:8081"
  collect:
    test:
      type: counter

```
</p>
</details>

<details><summary>worker.php</summary>
<p>

```php
<?php

use Spiral\Goridge;
use Spiral\RoadRunner;
use Nyholm\Psr7\Factory;

ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

$worker = new RoadRunner\Http\PSR7Worker(
	RoadRunner\Worker::create(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory(),
	new Factory\Psr17Factory()
);

$metrics = new RoadRunner\Metrics\Metrics(
	Goridge\RPC\RPC::create(RoadRunner\Environment::fromGlobals()->getRPCAddress())
);

while ($req = $worker->waitRequest()) {
	try {
		$rsp = new \Nyholm\Psr7\Response();
		$rsp->getBody()->write("hello world");

		$metrics->add('test', 1);

		$worker->respond($rsp);
	} catch (\Throwable $e) {
		$worker->getWorker()->error((string)$e);
	}
}

```
</p>
</details>

this started the roadrunner but failed on request
```
error 'metrics_plugin_add: collector test does not support method `Add`
```

<details><summary>response</summary>
<p>

```
1 error occurred:
	* error encoder: SoftJobError:
	sync_worker_exec_payload: Spiral\Goridge\RPC\Exception\ServiceException: error 'metrics_plugin_add: collector test does not support method `Add`; metrics_plugin_add: collector test does not support method `Add`' on tcp://127.0.0.1:6001 in /repo/vendor/spiral/goridge/src/RPC/RPC.php:120
Stack trace:
#0 /repo/vendor/spiral/goridge/src/RPC/RPC.php(93): Spiral\Goridge\RPC\RPC->decodeResponse(Object(Spiral\Goridge\Frame))
#1 /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php(44): Spiral\Goridge\RPC\RPC->call('Add', Array)
#2 /repo/worker.php(26): Spiral\RoadRunner\Metrics\Metrics->add('test', 1)
#3 {main}

Next Spiral\RoadRunner\Metrics\Exception\MetricsException: error 'metrics_plugin_add: collector test does not support method `Add`; metrics_plugin_add: collector test does not support method `Add`' on tcp://127.0.0.1:6001 in /repo/vendor/spiral/roadrunner-metrics/src/Metrics.php:46
Stack trace:
#0 /repo/worker.php(26): Spiral\RoadRunner\Metrics\Metrics->add('test', 1)
#1 {main}

```
</p>
</details>

<details><summary>rr output</summary>
<p>

```
2021-03-04T08:48:57.240Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 19}
2021-03-04T08:48:57.261Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 20}
2021-03-04T08:48:57.282Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 21}
2021-03-04T08:48:57.303Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 22}
2021-03-04T08:48:57.303Z	DEBUG	RPC	rpc/plugin.go:86	Started RPC service	{"address": "tcp://127.0.0.1:6001", "services": ["informer", "resetter", "metrics"]}
2021-03-04T08:49:02.196Z	INFO	metrics	metrics/rpc.go:29	adding metric	{"name": "test", "value": 1, "labels": []}
2021-03-04T08:49:02.197Z	DEBUG	server	server/plugin.go:226	worker destructed	{"pid": 19}
2021-03-04T08:49:02.228Z	DEBUG	server	server/plugin.go:224	worker constructed	{"pid": 28}

```
</p>
</details>

but it at least knows the metric because if i dont define it at all it throws
```
2021-03-04T08:58:43.907Z	ERROR	metrics	metrics/rpc.go:32	undefined collector	{"collector": "test"}
```

i am using binary from spiralscout/roadrunner:2.0.0 image and running it in php:8.0-cli image with ext-sockets

**Comment by Baldinof** [comment]
Hi, same for me on macOS (php 8.0.2), with same code snippets.

It seems that the php worker is started before the metrics plugin, it works with code like this:

```php
$declared = false;

while ($req = $worker->waitRequest()) {
    if (!$declared) {
        $metrics->declare(
            'test',
            Collector::counter()->withHelp('Test counter')
        );
        $declared = true;
    }
    
    $metrics->add('test', 1);
    // ...
```

**Comment by wolfy-j** [comment]
Are you getting a connection error or a declaration error?

**Comment by Baldinof** [comment]
It's a connection error on metric declaration :D 

I guess connection is opened on first RPC usage which happens to be the metric declaration. The stack trace is the same as @dstrop 

I also tried with a sleep, but it's still failing. It seems that the metric service is mounted after the worker is ready to handle requests.

```php
$metrics = new Metrics(RPC::create(Environment::fromGlobals()->getRPCAddress()));

sleep(4);

$metrics->declare('test', Collector::counter());

while ($req = $worker->waitRequest()) {
```

**Comment by dstrop** [comment]
i have found out why the metrics registered through rr config are not working

collectors from config are stored as `statsProvider`
https://github.com/spiral/roadrunner/blob/bd91ca0f3e444405f0f6cf9d1dabbeef93de2d85/plugins/metrics/plugin.go#L70-L81

but collectors registered through RPC are saved as `prometheus.Collector`
https://github.com/spiral/roadrunner/blob/bd91ca0f3e444405f0f6cf9d1dabbeef93de2d85/plugins/metrics/rpc.go#L241-L244

and when you try to use them you expect to receive `prometheus.Collector` 
but you may find `statsProvider` which will throw error in RR and then Exception in PHP
https://github.com/spiral/roadrunner/blob/bd91ca0f3e444405f0f6cf9d1dabbeef93de2d85/plugins/metrics/rpc.go#L30-L37

**Comment by 48d90782** [comment]
@dstrop now in beta -> https://github.com/spiral/roadrunner-binary/releases/tag/v2.0.2-beta.3
Thank you 👍🏻
