### ISSUE TITLE
[?] worker_watcher_wait: signal: killed; process_wait: signal: killed

### ISSUE THREAD

**Issue by febelery** [spiral/roadrunner#815]
```
local.ERROR: Uncaught ErrorException: file_put_contents(): Write of 522983 bytes failed with errno=32 Broken pipe in /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'file_put_conten...', '/home/user/www/...', 38)
#1 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents('php://stderr', '[php debug] <!d...')
#2 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\RoadRunner\Logger->write('[php debug] <!d...')
#3 /home/user/www/laravel/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\RoadRunner\Logger->log('debug', '<!doctype html>...', Array)
#4 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\RoadRunner\Logger->debug('<!doctype html>...')
#5 /home/user/www/laravel/vendor/symfony/http-foundation/Response.php(381): Spiral\RoadRunner\Internal\StdoutHandler::Spiral\RoadRunner\Internal\{closure}('<!doctype html>...', 1)
#6 /home/user/www/laravel/vendor/symfony/http-foundation/Response.php(394): Symfony\Component\HttpFoundation\Response->sendContent()
#7 /home/user/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\Component\HttpFoundation\Response->send()
#8 /home/user/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Spiral\Goridge\Exception\HeaderException))
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Spiral\Goridge\Exception\HeaderException))
#10 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: file_put_contents(): Write of 522983 bytes failed with errno=32 Broken pipe in /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'file_put_conten...', '/home/user/www/...', 38)
#1 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents('php://stderr', '[php debug] <!d...')
#2 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\\RoadRunner\\Logger->write('[php debug] <!d...')
#3 /home/user/www/laravel/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\\RoadRunner\\Logger->log('debug', '<!doctype html>...', Array)
#4 /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\\RoadRunner\\Logger->debug('<!doctype html>...')
#5 /home/user/www/laravel/vendor/symfony/http-foundation/Response.php(381): Spiral\\RoadRunner\\Internal\\StdoutHandler::Spiral\\RoadRunner\\Internal\\{closure}('<!doctype html>...', 1)
#6 /home/user/www/laravel/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\Response->sendContent()
#7 /home/user/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\\Component\\HttpFoundation\\Response->send()
#8 /home/user/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Spiral\\Goridge\\Exception\\HeaderException))
#9 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Spiral\\Goridge\\Exception\\HeaderException))
#10 {main}
  thrown at /home/user/www/laravel/vendor/spiral/roadrunner-worker/src/Logger.php:38)
[stacktrace]
#0 {main}
"}

```

**Comment by rustatian** [comment]
@febelery Signal `killed` means, that your PHP worker returned an exception and the worker was restarted.

**Comment by rustatian** [comment]
@febelery Could you please add a description of the issue?
